# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"(\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"<\n\x16RecommendationResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tmovies_id\x18\x02 \x03(\t2u\n\x0bRecommender\x12\x66\n\x13get_recommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\"\x00\x62\x06proto3')



_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
_RECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['RecommendationResponse']
RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:recommendation.RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommendation_pb2'
  # @@protoc_insertion_point(class_scope:recommendation.RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)

_RECOMMENDER = DESCRIPTOR.services_by_name['Recommender']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOMMENDATIONREQUEST._serialized_start=40
  _RECOMMENDATIONREQUEST._serialized_end=80
  _RECOMMENDATIONRESPONSE._serialized_start=82
  _RECOMMENDATIONRESPONSE._serialized_end=142
  _RECOMMENDER._serialized_start=144
  _RECOMMENDER._serialized_end=261
# @@protoc_insertion_point(module_scope)
