version: '3.8'

x-base-service: &base_service
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  networks:
    - ugc

x-redis: &base_redis
  <<: *base_service
  image: redis:7.0-alpine
  container_name: redis
  restart: unless-stopped
  expose:
    - ${REDIS_PORT}
  healthcheck:
    test: [ "CMD", "redis-cli","ping" ]
    interval: 30s
    timeout: 10s
    retries: 5

x-base-clickhouse-node: &base-clickhouse-node
  <<: *base_service
  image: yandex/clickhouse-server:22.1
  env_file: .env
  mem_limit: 1g
  expose:
    - 9000
  ulimits:
    memlock:
      soft: -1
      hard: -1
  depends_on:
    - zookeeper-clickhouse
  healthcheck:
    test: curl http://x-base-clickhouse-node:8123 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
    interval: 30s
    timeout: 10s
    retries: 5
  
x-base-kafka: &base_kafka
  <<: *base_service
  image: confluentinc/cp-kafka:7.3.0
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./kafka/start.sh:/tmp/start.sh
  command: "bash -c 'if [ ! -f /tmp/start.sh ]; then echo \"ERROR: Did you forget the start.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/start.sh && /etc/confluent/docker/run ; fi'"


services:

  nginx:
    <<: *base_service
    image: nginx:1.23.1-alpine
    container_name: nginx
    profiles:
      - dev_ugc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/producer_storage.conf:/etc/nginx/conf.d/producer_storage.conf:ro
      - ./nginx/static/errors:/var/www/errors/:ro
      - ./nginx/static/log/access_log:/var/log/nginx/access.log:rw
      - ./nginx/static/log/error_log:/var/log/nginx/error.log:rw
    depends_on:
      producer-storage:
        condition: service_healthy
    ports:
      - ${PRODUCER_STORAGE_PORT}:${PRODUCER_STORAGE_PORT}


  redis:
    <<: *base_redis
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - redis-data:/data


  producer-storage:
    <<: *base_service
    build: ./backend/producer_storage
    container_name: producer-storage
    env_file: .env
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backend/producer_storage:/opt/content
    expose:
      - ${PRODUCER_STORAGE_PORT}
    healthcheck:
      test: curl http://producer-storage:${PRODUCER_STORAGE_PORT} >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5


  kafka01:
    <<: *base_kafka
    hostname: kafka01
    container_name: kafka01
    env_file: .env
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka01:9092,CONTROLLER://kafka01:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'


  kafka02:
    <<: *base_kafka
    hostname: kafka02
    container_name: kafka02
    env_file: .env
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka02:9092,CONTROLLER://kafka02:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'


  kafka03:
    <<: *base_kafka
    hostname: kafka03
    container_name: kafka03
    env_file: .env
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka03:9092,CONTROLLER://kafka03:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:9093,2@kafka02:9093,3@kafka03:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'


  schema-registry:
    <<: *base_service
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    depends_on:
      - kafka01
      - kafka02
      - kafka03
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka01:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/subjects || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3


  control-center:
    <<: *base_service
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    depends_on:
      - kafka01
      - kafka02
      - kafka03
      - ksqldb-server
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka01:9092'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: 'http://ksqldb-server:8088'
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: 'http://ksqldb-server:8088'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    healthcheck:
      test: curl http://control-center:9021 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 60s
      timeout: 30s
      retries: 15
  

  ksqldb-server:
    <<: *base_service
    image: confluentinc/ksqldb-server:0.28.2
    hostname: ksqldb-server
    container_name: ksqldb-server
    restart: unless-stopped
    depends_on:
      - kafka01
      - kafka02
      - kafka03
      - schema-registry
    profiles:
      - dev_ugc
      - dev_graduate
      - prod
    expose:
      - 8088
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka01:9092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: 'ksqldb'
      KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: "kafka01:9092"
      KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "_ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "_ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "_ksql-connect-statuses"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_PLUGIN_PATH: "/usr/share/kafka/plugins"


  ksqldb-cli:
    <<: *base_service
    image: confluentinc/cp-ksqldb-cli:7.3.0
    container_name: ksqldb-cli
    profiles:
      - dev_ugc
      - dev_graduate
    depends_on:
      - kafka01
      - kafka02
      - kafka03
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true


  zookeeper-clickhouse:
    <<: *base_service
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper-clickhouse
    container_name: zookeeper-clickhouse
    profiles:
      - clickhouse
      - dev_ugc
      - dev_graduate
      - prod
    environment:
      ZOOKEEPER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - clickhouse-zookeeper:/var/lib/zookeeper
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1


  clickhouse-initer:
    <<: *base_service
    build: ./backend/clickhouse_initer
    container_name: clickhouse-initer
    env_file: .env
    profiles: 
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./backend/clickhouse_initer/mapping:/opt/clickhouse_initer/mapping:ro
    depends_on:
      clickhouse-node1:
        condition: service_healthy
      clickhouse-node2:
        condition: service_healthy
      clickhouse-node3:
        condition: service_healthy
      clickhouse-node4:
        condition: service_healthy
 

  clickhouse-node1:
    <<: *base-clickhouse-node
    container_name: clickhouse-node1
    profiles:
      - clickhouse
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - ./clickhouse/config/metrika.xml:/etc/metrika.xml
      - ./clickhouse/config/node1:/etc/clickhouse-server
    ports:
      - "9000:9000"

  clickhouse-node2:
    <<: *base-clickhouse-node
    container_name: clickhouse-node2
    profiles:
      - clickhouse
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - ./clickhouse/config/metrika.xml:/etc/metrika.xml
      - ./clickhouse/config/node2:/etc/clickhouse-server


  clickhouse-node3:
    <<: *base-clickhouse-node
    container_name: clickhouse-node3
    profiles:
      - clickhouse
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - ./clickhouse/config/metrika.xml:/etc/metrika.xml
      - ./clickhouse/config/node3:/etc/clickhouse-server


  clickhouse-node4:
    <<: *base-clickhouse-node
    container_name: clickhouse-node4
    profiles:
      - clickhouse
      - dev_ugc
      - dev_graduate
      - prod
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./clickhouse/initdb:/docker-entrypoint-initdb.d
      - ./clickhouse/config/metrika.xml:/etc/metrika.xml
      - ./clickhouse/config/node4:/etc/clickhouse-server


networks:
  ugc:
    driver: bridge


volumes:
  redis-data:
  clickhouse-zookeeper:
