version: '3.8'

x-base-service: &base_service
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
#    - /etc/timezone:/etc/timezone:ro
  networks:
    - recommended

services:
  nginx:
    <<: *base_service
    image: nginx:1.23.1-alpine
    container_name: nginx
    profiles:
      - dev_recom
    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d/:ro
      - ./nginx/static/errors:/var/www/errors/:ro
      - ./nginx/static/log/access_log:/var/log/nginx/access.log:rw
      - ./nginx/static/log/error_log:/var/log/nginx/error.log:rw
    ports:
      - ${SPARK_MASTER_WEB_PORT}:${SPARK_MASTER_WEB_PORT}

  spark-master:
    <<: *base_service
    image: bitnami/spark:3.2.3-debian-11-r19
    container_name: spark-master
    hostname: spark-master
    restart: on-failure
    profiles:
      - dev_recom
      - dev_graduate
      - prod
    expose:
      - ${SPARK_MASTER_WEB_PORT}
      - ${SPARK_MASTER_PORT}
    environment:
      - SPARK_MODE=master
    volumes:
      - .:/work
    healthcheck:
      test: curl http://spark-master:${SPARK_MASTER_WEB_PORT} >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker01:
    <<: *base_service
    image: bitnami/spark:3.2.3-debian-11-r19
    container_name: spark-worker01
    hostname: spark-worker01
    restart: on-failure
    profiles:
      - dev_recom
      - dev_graduate
      - prod
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:${SPARK_MASTER_PORT}

  spark-worker02:
    <<: *base_service
    image: bitnami/spark:3.2.3-debian-11-r19
    container_name: spark-worker02
    hostname: spark-worker02
    restart: on-failure
    profiles:
      - dev_recom
      - dev_graduate
      - prod
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:${SPARK_MASTER_PORT}

  spark-worker03:
    <<: *base_service
    image: bitnami/spark:3.2.3-debian-11-r19
    container_name: spark-worker03
    hostname: spark-worker03
    restart: on-failure
    profiles:
      - dev_recom
      - dev_graduate
      - prod
    depends_on:
      spark-master:
        condition: service_healthy
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:${SPARK_MASTER_PORT}


  jupyter-notebook:
    <<: *base_service
    image: jupyter/pyspark-notebook:java-17.0.5
    container_name: jupyter-notebook
    hostname: jupyter-notebook
    depends_on:
      spark-master:
        condition: service_healthy
    volumes:
      - ./jupyter-notebook/work:/home/jovyan/work
    profiles:
      - dev_recom
      - dev_graduate
    ports:
      - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}


networks:
  recommended:
    driver: bridge
