@startuml
autonumber
skinparam sequence {
	ParticipantPadding 20
	MessageAlign center
	skinparam BoxPadding 20
}

title New event from any of Online Movies API

box Apache Airflow
participant Scheduler as sch order 10
box DAG
participant ETL as etl order 20
participant ALS_Top as als order 30
participant Saver as sv order 35
end box
end box
collections Clickhouse as cl order 40
collections "Apache Spark" as spark order 41 #FFFF99
participant MoviesAdminAPI as a_api order 42
queue MongoDB as mng order 50
participant ContentAPI as c_api order 60
actor Frontend as frn order 70

sch -> etl
etl -> cl
return analytics_raw_data

etl -> etl: transform

'api_p -> api_n: event
'note left
'name_of_event_source
'name_type_event
'context
'created
'end note
'api_n -> q: NewEvent
'q -> b: NewEvent

'group #ebfafa Build email
'loop #c2f0f0 for message in queue
'q -> b: message
'b -> api_a: get user data
'note left
'user_id,
'name_event: str,
'end note
'return user
'note left
'None if not permissions for this event or inappropriate timezone
'user_email, user_name
'end note
'alt #c2f0f0 user not None
'b -> db: get type_event data (message.name_event)
'return type_event data
'note left
'subject, template
'end note
'b -> b: render email_text
'b -> q: email_message_for_send
'note right
'message.likes_request_date,
'message.review_id,
'email_text
'end note
'end alt
'end loop
'end group
'
'loop #fff2e6 Send email
'q -> s: message
's -> em: message
'em -> s: OK
'note right
'message.review_id,
'likes_request_date
'end note
'end loop

@enduml
