@startuml
autonumber
skinparam sequence {
	ParticipantPadding 20
	MessageAlign center
	skinparam BoxPadding 20
}

title Create recommendation for users

box Apache Airflow
participant Scheduler as sch order 10
box DAG
participant ETL as etl order 20
participant ALS_Top as als order 30
participant Saver as sv order 35
end box
end box
collections Clickhouse as cl order 40
collections "Apache Spark" as spark order 41 #FFFF99
participant MoviesAdminAPI as a_api order 42
queue MongoDB as mng order 50

sch -> etl
etl -> cl
return analytics_raw_data

etl -> spark: analytics_raw_data
return: analytics_dataframe

etl -> a_api
return metadata: movies duration
etl -> spark: metadata
return analytics_metrics_dataframe

etl -> als: analytics_metrics_dataframe
als -> spark: analytics_metrics_dataframe
return prediction_top_dataframe

als -> sv: prediction_top_dataframe

sv -> mng: prediction_top_data
return ok

@enduml
